package initialize

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mschulkind-oss/swarf/internal/config"
	"github.com/mschulkind-oss/swarf/internal/console"
	"github.com/mschulkind-oss/swarf/internal/exclude"
	"github.com/mschulkind-oss/swarf/internal/gitexec"
	"github.com/mschulkind-oss/swarf/internal/link"
	"github.com/mschulkind-oss/swarf/internal/paths"
)

var ErrNotGitRepo = errors.New("not inside a git repository")

// EnsureStore initializes the central store (backup mirror) if it doesn't exist.
// Also configures repo-local git identity so commits can succeed without a
// global ~/.gitconfig — the store is internal machinery, not an author's
// commit log, so hard-coding an identity here is fine.
func EnsureStore(hostRoot string, gc *config.GlobalConfig) error {
	if paths.IsDir(paths.StoreDir) && gitexec.IsRepo(paths.StoreDir) {
		ensureStoreGitIdentity()
		return nil
	}

	if err := os.MkdirAll(paths.StoreDir, 0o755); err != nil {
		return fmt.Errorf("create store: %w", err)
	}
	if err := gitexec.Init(paths.StoreDir); err != nil {
		return fmt.Errorf("git init store: %w", err)
	}

	ensureStoreGitIdentity()

	if gc.Backend == "git" && gc.Remote != "" {
		gitexec.AddRemote(paths.StoreDir, "origin", gc.Remote)
	}

	WriteStoreReadme()

	console.Ok(fmt.Sprintf("Created central store at %s", paths.StoreDir))
	return nil
}

// ensureStoreGitIdentity gives the store a local user.email / user.name so
// `git commit` works even when the user has no global git identity (common
// in containers and fresh machines). Idempotent: re-setting the same value
// is a no-op.
func ensureStoreGitIdentity() {
	if gitexec.ConfigGet(paths.StoreDir, "user.email") == "" {
		_ = gitexec.ConfigSet(paths.StoreDir, "user.email", "swarf@localhost")
	}
	if gitexec.ConfigGet(paths.StoreDir, "user.name") == "" {
		_ = gitexec.ConfigSet(paths.StoreDir, "user.name", "swarf")
	}
}

// WriteStoreReadme creates or updates a README.md in the central store
// with an overview of registered projects and how swarf works.
func WriteStoreReadme() {
	drawers := config.ReadDrawers()
	gc := config.ReadGlobalConfig()

	var b strings.Builder
	b.WriteString("# swarf store\n\n")
	b.WriteString("This repository is a [swarf](https://github.com/mschulkind-oss/swarf) backup store.\n")
	b.WriteString("It is managed automatically — do not edit files here directly.\n\n")
	b.WriteString("Each subdirectory mirrors one project's `swarf/` directory.\n")
	b.WriteString("The daemon watches for changes and commits them here, then pushes to this remote.\n\n")

	if len(drawers) > 0 {
		b.WriteString("## Projects\n\n")
		b.WriteString("| Project | Local Path |\n")
		b.WriteString("|---------|------------|\n")
		for _, d := range drawers {
			b.WriteString(fmt.Sprintf("| `%s` | `%s` |\n", d.Slug, d.Host))
		}
		b.WriteString("\n")
	}

	b.WriteString("## How it works\n\n")
	b.WriteString("```\n")
	b.WriteString("project/swarf/  ──mirror──▶  ~/.local/share/swarf/<project>/  ──push──▶  this repo\n")
	b.WriteString("```\n\n")
	b.WriteString("1. You write files into `swarf/` in any registered project\n")
	b.WriteString("2. The swarf daemon detects changes via filesystem watchers\n")
	b.WriteString("3. After a debounce period, it mirrors to this store and commits\n")
	b.WriteString("4. On a new machine: `swarf pull` + `swarf init` restores everything\n\n")

	if gc != nil {
		b.WriteString("## Config\n\n")
		b.WriteString(fmt.Sprintf("- **Backend:** %s\n", gc.Backend))
		if gc.Remote != "" {
			b.WriteString(fmt.Sprintf("- **Remote:** `%s`\n", gc.Remote))
		}
		b.WriteString(fmt.Sprintf("- **Debounce:** %s\n", gc.Debounce))
		if len(gc.AutoSweep) > 0 {
			b.WriteString(fmt.Sprintf("- **Auto-sweep:** %s\n", strings.Join(gc.AutoSweep, ", ")))
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n\n")
	b.WriteString("*This file is regenerated by swarf. [Learn more](https://github.com/mschulkind-oss/swarf)*\n")

	os.WriteFile(filepath.Join(paths.StoreDir, "README.md"), []byte(b.String()), 0o644)
}

// Run initializes swarf for the current project. Idempotent: calling it
// again in an already-set-up project re-registers the drawer, refreshes
// excludes, and recreates any missing symlinks — the "fix my broken state"
// path users hit after deleting a file by hand or running 'swarf init' in
// a project whose store content came from a pull on another machine.
//
// Seeding behavior: whenever the central store has content for this
// project's slug, we copy it into project/swarf/. The copy is additive
// (never deletes local files) so a user with their own work-in-progress
// in swarf/ won't lose it. The ongoing daemon mirror handles the
// destructive direction later.
func Run(globalConfig *config.GlobalConfig) error {
	hostRoot := gitexec.GetRepoRoot("")
	if hostRoot == "" {
		return ErrNotGitRepo
	}

	sd := paths.SwarfDir(hostRoot)
	slug := paths.ProjectSlug(hostRoot)

	firstTime := true
	if fi, err := os.Lstat(sd); err == nil && (fi.IsDir() || fi.Mode()&os.ModeSymlink != 0) {
		firstTime = false
	}

	if err := EnsureStore(hostRoot, globalConfig); err != nil {
		return err
	}

	// Seed project/swarf/ from the store whenever the store has content for
	// this slug. Covers:
	//   - First-time init on a new project (store empty, no-op).
	//   - First-time init after 'swarf pull' on a fresh machine, where
	//     the store already holds this project's files from a peer.
	//   - Re-init over a manually-created or stale swarf/ dir that's
	//     missing files the store has. copyDir is additive, so any
	//     local-only files the user has are preserved.
	storeProject := paths.StoreProjectDir(hostRoot)
	seededCount := 0
	if paths.IsDir(storeProject) {
		n, err := copyDirInto(storeProject, sd)
		if err != nil {
			return fmt.Errorf("seed from store: %w", err)
		}
		seededCount = n
	}

	if err := os.MkdirAll(paths.LinksDir(hostRoot), 0o755); err != nil {
		return fmt.Errorf("create .links/: %w", err)
	}

	exclude.UpdateExcludes(hostRoot, nil)
	config.RegisterDrawer(slug, hostRoot)

	// Re-create any missing symlinks for files under swarf/.links/.
	link.Run(hostRoot, true)

	if firstTime {
		console.Ok(fmt.Sprintf("Initialized swarf for %s", slug))
	} else {
		console.Ok(fmt.Sprintf("Refreshed swarf setup for %s", slug))
	}
	if seededCount > 0 {
		console.Ok(fmt.Sprintf("Seeded %d file(s) from store/%s/ into %s/", seededCount, slug, paths.SwarfDirName))
	}
	console.Infof("  Backend: %s", globalConfig.Backend)
	if globalConfig.Remote != "" {
		console.Infof("  Remote: %s", globalConfig.Remote)
	}
	return nil
}

// copyDirInto recursively copies src into dst (additive — never deletes
// anything in dst). Returns the number of files written. Used for seeding
// project/swarf/ from the store.
func copyDirInto(src, dst string) (int, error) {
	written := 0
	err := filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		rel, _ := filepath.Rel(src, path)
		if rel == "." {
			return os.MkdirAll(dst, 0o755)
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return nil
		}
		if err := os.WriteFile(target, data, info.Mode()); err != nil {
			return nil
		}
		written++
		return nil
	})
	return written, err
}
