package initialize

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mschulkind-oss/swarf/internal/config"
	"github.com/mschulkind-oss/swarf/internal/console"
	"github.com/mschulkind-oss/swarf/internal/exclude"
	"github.com/mschulkind-oss/swarf/internal/gitexec"
	"github.com/mschulkind-oss/swarf/internal/link"
	"github.com/mschulkind-oss/swarf/internal/paths"
)

var (
	ErrNotGitRepo         = errors.New("not inside a git repository")
	ErrAlreadyInitialized = errors.New("swarf is already initialized here")
)

// EnsureStore initializes the central store (backup mirror) if it doesn't exist.
func EnsureStore(hostRoot string, gc *config.GlobalConfig) error {
	if paths.IsDir(paths.StoreDir) && gitexec.IsRepo(paths.StoreDir) {
		return nil
	}

	if err := os.MkdirAll(paths.StoreDir, 0o755); err != nil {
		return fmt.Errorf("create store: %w", err)
	}
	if err := gitexec.Init(paths.StoreDir); err != nil {
		return fmt.Errorf("git init store: %w", err)
	}

	for _, key := range []string{"user.name", "user.email"} {
		if val := gitexec.ConfigGet(hostRoot, key); val != "" {
			gitexec.ConfigSet(paths.StoreDir, key, val)
		}
	}

	if gc.Backend == "git" && gc.Remote != "" {
		gitexec.AddRemote(paths.StoreDir, "origin", gc.Remote)
	}

	WriteStoreReadme()

	console.Ok(fmt.Sprintf("Created central store at %s", paths.StoreDir))
	return nil
}

// WriteStoreReadme creates or updates a README.md in the central store
// with an overview of registered projects and how swarf works.
func WriteStoreReadme() {
	drawers := config.ReadDrawers()
	gc := config.ReadGlobalConfig()

	var b strings.Builder
	b.WriteString("# swarf store\n\n")
	b.WriteString("This repository is a [swarf](https://github.com/mschulkind-oss/swarf) backup store.\n")
	b.WriteString("It is managed automatically — do not edit files here directly.\n\n")
	b.WriteString("Each subdirectory mirrors one project's `swarf/` directory.\n")
	b.WriteString("The daemon watches for changes and commits them here, then pushes to this remote.\n\n")

	if len(drawers) > 0 {
		b.WriteString("## Projects\n\n")
		b.WriteString("| Project | Local Path |\n")
		b.WriteString("|---------|------------|\n")
		for _, d := range drawers {
			b.WriteString(fmt.Sprintf("| `%s` | `%s` |\n", d.Slug, d.Host))
		}
		b.WriteString("\n")
	}

	b.WriteString("## How it works\n\n")
	b.WriteString("```\n")
	b.WriteString("project/swarf/  ──mirror──▶  ~/.local/share/swarf/<project>/  ──push──▶  this repo\n")
	b.WriteString("```\n\n")
	b.WriteString("1. You write files into `swarf/` in any registered project\n")
	b.WriteString("2. The swarf daemon detects changes via filesystem watchers\n")
	b.WriteString("3. After a debounce period, it mirrors to this store and commits\n")
	b.WriteString("4. On a new machine: `swarf clone` + `swarf init` restores everything\n\n")

	if gc != nil {
		b.WriteString("## Config\n\n")
		b.WriteString(fmt.Sprintf("- **Backend:** %s\n", gc.Backend))
		if gc.Remote != "" {
			b.WriteString(fmt.Sprintf("- **Remote:** `%s`\n", gc.Remote))
		}
		b.WriteString(fmt.Sprintf("- **Debounce:** %s\n", gc.Debounce))
		if len(gc.AutoSweep) > 0 {
			b.WriteString(fmt.Sprintf("- **Auto-sweep:** %s\n", strings.Join(gc.AutoSweep, ", ")))
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n\n")
	b.WriteString("*This file is regenerated by swarf. [Learn more](https://github.com/mschulkind-oss/swarf)*\n")

	os.WriteFile(filepath.Join(paths.StoreDir, "README.md"), []byte(b.String()), 0o644)
}

// Run initializes swarf for the current project.
func Run(globalConfig *config.GlobalConfig) error {
	hostRoot := gitexec.GetRepoRoot("")
	if hostRoot == "" {
		return ErrNotGitRepo
	}

	sd := paths.SwarfDir(hostRoot)
	slug := paths.ProjectSlug(hostRoot)

	if fi, err := os.Lstat(sd); err == nil {
		if fi.IsDir() || fi.Mode()&os.ModeSymlink != 0 {
			return ErrAlreadyInitialized
		}
	}

	if err := EnsureStore(hostRoot, globalConfig); err != nil {
		return err
	}

	// Create swarf/ as a real directory in the project.
	// If the store already has content for this project (e.g., after clone),
	// seed the local swarf/ from the store mirror.
	storeProject := paths.StoreProjectDir(hostRoot)
	if paths.IsDir(storeProject) {
		if err := copyDir(storeProject, sd); err != nil {
			return fmt.Errorf("seed from store: %w", err)
		}
		console.Ok(fmt.Sprintf("Restored %s from store.", slug))
	}

	// Always ensure .links/ exists, even if the store didn't have one.
	if err := os.MkdirAll(paths.LinksDir(hostRoot), 0o755); err != nil {
		return fmt.Errorf("create .links/: %w", err)
	}

	exclude.UpdateExcludes(hostRoot, nil)
	config.RegisterDrawer(slug, hostRoot)

	// Re-create symlinks from swarf/.links/ (e.g. after clone + init).
	link.Run(hostRoot, true)

	console.Ok(fmt.Sprintf("Initialized swarf for %s", slug))
	console.Infof("  Backend: %s", globalConfig.Backend)
	if globalConfig.Remote != "" {
		console.Infof("  Remote: %s", globalConfig.Remote)
	}
	return nil
}

// copyDir recursively copies src into dst.
func copyDir(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		rel, _ := filepath.Rel(src, path)
		if rel == "." {
			return os.MkdirAll(dst, 0o755)
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		os.MkdirAll(filepath.Dir(target), 0o755)
		return os.WriteFile(target, data, info.Mode())
	})
}
